# vi: set ft=ruby :

$script = <<EOF
curl -sL -o /etc/yum.repos.d/khara-dm-writeboost.repo https://copr.fedoraproject.org/coprs/khara/dm-writeboost/repo/epel-7/khara-dm-writeboost-epel-7.repo
yum install --disablerepo=* --enablerepo=khara-dm-writeboost -y kmod-dm-writeboost writeboost dm-writeboost-tools
echo "wbdev /dev/vdb /dev/vdc writeback_threshold=70" > /etc/writeboosttab
echo "---- wbcreate ----"
wbcreate wbdev /dev/vdb /dev/vdc --reformat --writeback_threshold=70
echo "---- mkfs ----"
mkfs.xfs /dev/mapper/wbdev
mkdir /mnt/wb
mount /dev/mapper/wbdev /mnt/wb/
echo "---- wbstatus ----"
dmsetup status wbdev | wbstatus
echo "---- df ----"
df -hT
EOF

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
    libvirt.storage :file, :device => "vdb", :size => "10G", :type => "qcow2"
    libvirt.storage :file, :device => "vdc", :size => "10G", :type => "qcow2"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.synced_folder "../", "/home/vagrant/dm-writeboost-rpm",
  #  create: true, owner: "vagrant", group: "vagrant"
  config.vm.provision "shell", privileged: true, inline: $script
end
