FROM centos:7
MAINTAINER Kazuhisa Hara <kazuhisya@gmail.com>

RUN yum install -y --setopt=tsflags=nodocs \
        yum-utils rpmdevtools make epel-release kernel kernel-devel && \
    yum install -y --setopt=tsflags=nodocs dkms

WORKDIR /wb
COPY / /wb

RUN spectool -g ./dm-writeboost-dkms.spec && \
    mkdir -p dist/{BUILD,RPMS,SPECS,SOURCES,SRPMS,install} && \
    cp -pf *.tar.gz dist/SOURCES/
RUN rpmbuild -ba \
        --define "_topdir ${PWD}/dist" \
        --define "buildroot ${PWD}/dist/install" \
        --clean \
        dm-writeboost-dkms.spec
RUN yum install --disablerepo=* -y ./dist/RPMS/noarch/dm-*
