FROM centos:7
MAINTAINER Kazuhisa Hara <kazuhisya@gmail.com>

ENV KERNEL_VERSION="3.10.0-693.el7" \
    REPO="http://mirror.centos.org/centos-7/7.4.1708/os/x86_64/Packages"

RUN curl -OL ${REPO}/kernel-${KERNEL_VERSION}.x86_64.rpm && \
    curl -OL ${REPO}/kernel-devel-${KERNEL_VERSION}.x86_64.rpm && \
    curl -OL ${REPO}/kernel-headers-${KERNEL_VERSION}.x86_64.rpm && \
    curl -OL ${REPO}/kernel-abi-whitelists-${KERNEL_VERSION}.noarch.rpm
RUN yum install -y --setopt=tsflags=nodocs ./kernel* yum-utils rpmdevtools make gcc

WORKDIR /wb
COPY / /wb
RUN spectool -g ./dm-writeboost-kmod.spec && \
    mkdir -p dist/{BUILD,RPMS,SPECS,SOURCES,SRPMS,install} && \
    cp -pf *.tar.gz dist/SOURCES/ && \
    cp -pf *.sh dist/SOURCES/
RUN rpmbuild -ba \
        --define "_topdir ${PWD}/dist" \
        --define "buildroot ${PWD}/dist/install" \
        --clean \
        dm-writeboost-kmod.spec
RUN yum install --disablerepo=* -y ./dist/RPMS/x86_64/kmod-*

