FROM fedora:26
MAINTAINER Kazuhisa Hara <kazuhisya@gmail.com>

RUN dnf install -y --setopt=tsflags=nodocs \
    dnf-plugins-core rpmdevtools make kernel kernel-devel dkms

WORKDIR /wb
COPY / /wb

RUN spectool -g ./dm-writeboost-dkms.spec && \
    mkdir -p dist/{BUILD,RPMS,SPECS,SOURCES,SRPMS,install} && \
    cp -pf *.tar.gz dist/SOURCES/
RUN rpmbuild -ba \
        --define "_topdir ${PWD}/dist" \
        --define "buildroot ${PWD}/dist/install" \
        --clean \
        dm-writeboost-dkms.spec
RUN dnf install --disablerepo=* -y ./dist/RPMS/noarch/dm-*
