FROM centos:7
MAINTAINER Kazuhisa Hara <kazuhisya@gmail.com>

RUN yum install -y --setopt=tsflags=nodocs yum-utils rpmdevtools make vim bash-completion

WORKDIR /wb
COPY / /wb

RUN spectool -g writeboost.spec && \
    mkdir -p dist/{BUILD,RPMS,SPECS,SOURCES,SRPMS,install} && \
    cp -pf *.tar.gz dist/SOURCES/ && \
    cp -pf *.patch dist/SOURCES/
RUN rpmbuild -ba \
        --define "_topdir ${PWD}/dist" \
        --define "buildroot ${PWD}/dist/install" \
        --clean \
        writeboost.spec
RUN yum install --disablerepo=* -y ./dist/RPMS/noarch/writeboost*

